### ISSUE TITLE
Policies --> object and not array?

### ISSUE THREAD

**Issue by SabineGl** [datacontract/datacontract-specification#102]
Hi, if I use policies as array the link is not shown in a proper way in HTML.

I assume policies is supposed to be a type Object?

Otherwise I get a html view like this in **data contract manager**:

![image](https://github.com/user-attachments/assets/c93e0704-43d3-4951-8475-ec965e3d337c)

Config I used:
``` 
terms:
  usage: myUseage
  limitations: df
  billing: "free, monthly costs. ."
  noticePeriod: P6M
  Policies:
  - description: privacy
    url: https://my_link_to_my_privacy_policy
    
   ```

in **online data contract editor** "policy" is not even displayed:

![image](https://github.com/user-attachments/assets/7ab49b63-fd30-4821-939d-e2b9a17f224d)

I suppose it should be an object like "contact":

``` 
info:
  title: Party Channels
  version: 0.0.1
  status: proposed
  owner: urn:li:domain:CSV8A273D17
  contact:
    name: my.my@mail.com
    email: smy.my@mail.com
    url: https://git.dev.com/datacontracts/party-channels

```

**Comment by SabineGl** [comment]
Oh I see ... an object array??

**Comment by SabineGl** [comment]
correct config would be:

```  
policies:
    - description: Link to vvz
      type: privacy
      url: https://my-link.com   
 ```
