### ISSUE TITLE
isXXX

### ISSUE THREAD

**Issue by jgperrin** [datacontract/datacontract-specification#115]
ODCS v3 generator gives:

```yaml
  - name: customer_id
    logicalType: integer
    physicalType: integer
    isNullable: false
    isUnique: true
    primaryKey: true
    primaryKeyPosition: 1

```

ODCS elements are `nullable` and `unique` - we dropped the `is`.
