### ISSUE TITLE
Allow lists of quality specifications

### ISSUE THREAD

**Issue by stefannegele** [datacontract/datacontract-specification#12]
Users of the CLI would find it very helpful if various quality specifications were supported. 

```yaml
quality:
  - basic:
      weight: 0.2
      type: SodaCL
      specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-basic.yaml"
  - premium1:
      weight: 0.4
      type: SodaCL
      specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-premium1.yaml"
  - premium2:
      weight: 0.4
      type: SodaCL
      specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-premium2.yaml"
```

I suggest we support both - individual specifications or a list.

See also:
https://github.com/datacontract/cli/pull/3#discussion_r1358205380

**Comment by jochenchrist** [comment]
If we decide to support multiple quality definitions, I would prefer this structure to be consistent with examples:

```
quality:
  - name: basic
    type: SodaCL
    specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-basic.yaml"
  - name: premium1
    type: SodaCL
    specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-premium1.yaml"
  - name: premium2
    type: SodaCL
    specification: "$ref: https://github.com/data-engineering-helpers/data-contracts/blob/123b1310662557c469e091b646f64e47b938836f/datacontract.com/contracts/data-contract-flight-route-quality-premium2.yaml"
```
