### ISSUE TITLE
Feature: Support for Extending Models and Properties from Referred Business Definitions

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#125]
Introduce support for extending models or individual properties within a data contract from external, referred business definitions. This would enable schema reuse, specialization, and modular modeling of complex business entities, based on centrally managed definitions.

### Use Case:

Organizations often define canonical business entities (e.g., Customer, Product, Transaction) in a shared repository or registry. Data contracts for domain-specific products may need to build on these definitions by extending them—either by reusing and enriching a full model, or by referencing shared field definitions (e.g., a standardized address or money property).

### Proposed Syntax (Illustrative):

Extending a model:

```
models:
  EnrichedCustomer:
    extends:
      $ref: "https://example.com/models/Customer@v1.0.0"
    properties:
      enrichment_timestamp:
        type: string
        format: date-time
```

Extending a property:

```
models:
  Order:
    properties:
      customer:
        extends:
          $ref: "https://example.com/models/Customer@v1.0.0"
      status:
        type: string
        enum: ["open", "closed"]
```

### Expected Behavior:

- The contract processor resolves $ref values, either on a model or property level, and applies extension or composition rules accordingly.
- The resulting model or property should reflect a valid merge between the base definition and local overrides or enrichments.

Open Questions:
- Should merging behavior follow JSON Schema composition rules (allOf, anyOf), or support a simplified domain-specific strategy?
- What validation rules apply when extensions override fields or constraints?

**Comment by garrettsutula** [comment]
I like the idea of using `$ref` both for this and also to specify typed array items, maybe consider the `order_tbl` schema as a physical model for a document database:

```yaml
...
schema:
  - id: orders_document
    name: orders
    properties:
      - id: order_customer_id
        name: customer_id
      - id: order_items
        name: order_items
        type: array
        items:
          $ref: schema/order_items
          # $ref: ../orders/contract.odcs.yaml#/schema/order_items
          # $ref: https://schema.companyname.com/orders/1.0.3/contract.odcs.yaml"
...
```

I think this idea is relevant for many physical schemas (e.g. message envelope + payload, document, etc.) as well as logical schemas.
