### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#14]
```yaml
components:
  definitions:
    customer_id:
      context: checkout
      name: customer_id
      title: Customer ID
      type: string
      description: Only registered webshop customers have a customer_id
      example: 34758934758934
      pii: true
      classification: sensitive
      tags: []
```
