### ISSUE TITLE
Add constraints to field object

### ISSUE THREAD

**Issue by stefannegele** [datacontract/datacontract-specification#17]
It would be nice to have the possibility to add field constraints to a [Field Object](https://datacontract.com/#field-object) because with the current state of the specification, the data contract cannot contain constraint (e.g. nullability) information on a field. 

Since field existence (`required` or `nullable`) and uniqueness (`unique`) are so omnipresent and important, I would make them first level citizens in the field object. All other constraints can live in a field `constraints` [similar to how dbt does it](https://docs.getdbt.com/reference/resource-properties/constraints). My idea how to store such information in the contract is:

```yaml
models:
  my_table:
    description: contains data
    fields:
      my_column:
        description: contains values
        type: text
        required: true # this is new
        unique: true # this is new
        constraints: # this is new
          primary_key_constraint:
            type: primary_key
          check_constraint:
            type: check
            expression: "my_column == my_column"
    type: table
```
