### ISSUE TITLE
Add URL schema type explicitly

### ISSUE THREAD

**Issue by tarys** [datacontract/datacontract-specification#23]
# Status Quo
Currently, [supported schema types](https://github.com/datacontract/datacontract-specification?tab=readme-ov-file#schema-object) are:
1. `dbt`
2. `bigquery`
3. `json-schema`
4. `sql-ddl`
5. `avro`
6. `protobuf`
7. `custom`

# Motivation
Real-world schemas could be quite large + single data product might span multiple database tables, Kafka topics, etc.
Thus, direct inline inclusion of schema definition can make data contract's YAML-flie quite large and inconvenient to be read by human.
It's also true, that that is not a problem in case YAML-file is parsed automatically.

# Proposal
Add URL schema type explicitly with validation for `specification` field:
```yml
schema:
  type: schema-url
  specification: https://schemaregistry.mycompany.com/path/to/actual/model/description/and/definition
```

# Alternatives
Currently such result could be achieved via:
```yml
schema:
  type: custom
  specification: <string>
```
However, such approach is missing explicit validation of URL format of `specification` field and is less comprehensive semantically.
