### ISSUE TITLE
Add anonymization to field

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#24]
```
models:
  orders:
    fields:
      customer_email:
        type: string
        format: email
        pii: true
        anonymization: masked # other options: none (default), hashed
```

I'm not sure whether this should be referenced via the definition.
