### ISSUE TITLE
Billing as structured field

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#3]
To automate billing, a billing policy should be represented in a structured form.

Typical billing policies are:
- free
- pay per query
- pay per megabyte scanned
- pay per month

**Option 1: Additional Field `billingPolicy`**

```yaml
terms:
  billing: Monthly flat price
  billingPolicy:
    amount: 5000
    currency: USD
    unit: MONTH
```

```yaml
terms:
  billing: Pay per use
  billingPolicy:
    amount: 0.005
    currency: USD
    unit: MEGABYTE
```

```yaml
terms:
  billing: Free to use
  billingPolicy:
    amount: 0
    currency: USD
    unit: MONTH
```

**Option 2: Reuse field `billing`**

The field `billing` may be either a string or a complex type (`anyOf`)

```yaml
terms:
  billing: Free
```

```yaml
terms:
  billing:
    amount: 5000
    currency: USD
    unit: MONTH
```
