### ISSUE TITLE
Add model.title / field.title

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#31]
```yaml
models:
  order:
    type: "table"
    title: "Purchase Order" # NEW
    fields:
      order_id:
        type: text
        title: "Order ID" # NEW
```

Feels natural to allow the user to provide a more human friendly name.

We already support `title` in the definition anyway.
