### ISSUE TITLE
Add field.primary and field.references

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#32]
```yaml
models:
  orders:
    fields:
      order_id:
        type: text
        primary: true
  line_items:
    fields:
       line_item_id:
         type: bigint
         primary: true
       order_id:
         type: text
         references: orders.order_id
```
