### ISSUE TITLE
Service Level Objectives

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#4]
Do we need service level objectives as an extra section?

Typical SLOs might be

- Uptime / Availability
- Freshness
- Completeness
- Retention
- Performance
- Volume
- Support Times

Many of these SLOs could also be expressed as executable Quality Checks, others are more descriptive.

**Comment by visenger** [comment]
I think, yes, we will need an extra section for SLOs. 
Not everything can be expressed via quality checks.
Making SLOs explicit is a clear communication of what is expected.

**Comment by jochenchrist** [comment]
Possible spec:

**Option 1: Simple Map**

```yaml
serviceLevelObjectives:
  uptime: > 99.9%
  freshness: < 24h
  retention: 30 days
  supportTimes: 09-17 PST on business days
```

**Option 2: Complex Map**

```yaml
serviceLevelObjectives:
  uptime: 
    description: The availbility time of data access
    value: > 99.9%
```

**Option 3: List**

```yaml
serviceLevelObjectives:
  - name: uptime
    description: The availbility time of data access
    value: > 99.9%
  - name: Support Times
    value: 09-17 PST on business days
```
