### ISSUE TITLE
Allow precision and scale for decimal

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#41]
Currently, we cannot set precision and scale for a decimal, but this is normally required for SQL based storage.

Suggestion: Adding two fields to the field definition like this:

```
models:
  orders:
    description: One record per order. Includes cancelled and deleted orders.
    type: table
    fields:
      order_id:
        type: decimal
        precision: 38
        scale: 0
```
