### ISSUE TITLE
Add arn for server type s3

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#43]
The ARN of a bucket could be added to the server object:

```yaml
servers:
  production:
    type: s3
    location: s3://datacontract-example-orders-latest/data/{model}/*.json
    format: json
    delimiter: new_line
    arn: arn:aws:s3:::lambda-artifacts-d1bcf3b6d4b5121d #NEW
```

It's AWS specific, but might be helpful anyway for the 80% case. But not totally sure if this is necessary.
