### ISSUE TITLE
Add glue catalog server type

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/datacontract-specification#46]
Hello, 
I would like to know if it would be possible to add Glue Catalog metastore as a supported server type in the specification ?
It would look to something like that:

```
servers:
  development:
    type: glue
    account: "1234-5678-9012"
    database: my_database

```
