### ISSUE TITLE
Move dataProduct and outputPort to servers

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#5]
To make data contract independent from data mesh / data products, move data products to `servers` as one possible `type`:

```
servers:
  production:
    type: dataproduct
    dataProduct: orders
    outputPort: bigquery_orders_latest_npii_v1
```

**Comment by jochenchrist** [comment]
Alternative Option, just move the outputport:

```
servers:
  production:
    type: outputport
    outputPort: bigquery_orders_latest_npii_v1
```

**Comment by simonharrer** [comment]
We removed outputPort and dataProduct from the specification. You can add this as extensions for a given server. The Data Mesh Manager (www.datamesh-manager.com) uses `dataProductId` and `outputPortId` as follows:

```
servers:
  production:
    type: s3
    location: s3://asdf/orders/...
    dataProductId: orders
    outputPortId: bigquery_orders_latest_npii_v1
```
