### ISSUE TITLE
Scope / Filter / Selection of a data model

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#67]
Describe, which data in included in a model.

```
model:
  orders_emea:
    fields: ...
    filter: 
      expression: country_code in ['DE', 'AT', ...]
```

**Comment by ArtyomyuS** [comment]
Open pull-request: https://github.com/datacontract/datacontract-specification/pull/91

**Comment by simonharrer** [comment]
@ArtyomyuS I'm wondering if this is not just a quality check. A quality check that ensures that `country_code = 'DE'` in the model of a data contract. One could mark this as a filter so it can be used for code generation in your case. This would make the addition of a `filter` element superfluous. What do you think?

**Comment by ArtyomyuS** [comment]
Hey @simonharrer , by considering quality check for this aspect I guess yes filter it is not required anymore. However in this particular case. If the checks apply to the model by creating the data product, then all checks should apply. Not sure all of them should be part of the code generation. Or should they all be? :)

**Comment by ArtyomyuS** [comment]
Hey @jochenchrist and @simonharrer any updates on the above? Thanks 🙏

**Comment by jochenchrist** [comment]
In the upcoming release v1.1.0, we are also planning to support lineage:
https://github.com/datacontract/datacontract-specification/tree/develop/v1?tab=readme-ov-file#lineage-object 

A filter condition is also a lineage FILTER transformation:

```
        lineage:
          inputFields:
            - namespace: com.example.service.checkout
              name: checkout_db.orders
              field: order_id
              transformations:
                - type: DIRECT
                  subtype: IDENTITY
                  description: The order ID from the checkout order
            - namespace: com.example.service.checkout
              name: checkout_db.orders
              field: region
                - type: INDIRECT
                  subtype: FILTER
                  description: region = 'US'
```

**Comment by jochenchrist** [comment]
I think quality and lineage are sufficient for the use case.

If you need an SQL condition for your use case or tooling, you can consider specifying a config option:

```
model:
  orders_emea:
    fields: ...
    config:
      sqlWhereCondition: country_code in ['DE', 'AT', ...]
```
