### ISSUE TITLE
Partinioning and FileFormat for server type s3

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#7]
```yaml
servers:
  production:
    type: s3
    location: s3://location-to-bucket/
    partitioning: /year=$year/month=$month
    fileformat: ndjson # delta, parquet, json, ndjson, ...
```

**Comment by stefannegele** [comment]
```
servers:
  production:
    type: s3
    location: s3://location-to-bucket/my-path/year=$year/month=$month
    partitionKeys:
        - name: year
           type: string
        - name: month
           type: string
    format: ndjson # delta, parquet, json, ndjson, ...
```
