### ISSUE TITLE
Add environment as an optional field for every server

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#75]
```yaml
servers:
  dbx_prod:
    type: databricks
    catalog: my-catalog
    schema: my-schema
    environment: prod # new
```
