### ISSUE TITLE
Support Confluent Schema Registry server

### ISSUE THREAD

**Issue by databius** [datacontract/datacontract-specification#8]
Add new Confluent Schema Registry server. Example:
```
servers:
  my-stage:
    type: confluent_schema_registry
    host:
    subjects:
      compatibility:
      name:
      type:
      schema:
```
