### ISSUE TITLE
Data Type map

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#80]
There currently is no `map` data type in the spec. https://datacontract.com/#data-types 

@jochenchrist three options: 
1. follow JSON Schema: type `object` with `additionalProperties` where one can define the types of the values
2. follow Avro Schema: introduce a dedicated data type `map` with `values` field to define the substructures
3. no map type at all

Not sure where we should be heading. Any thoughts?

_Originally posted by @simonharrer in https://github.com/datacontract/datacontract-cli/issues/324#issuecomment-2225620697_

**Comment by jochenchrist** [comment]
Let's analyze, how maps would be handled on different server types and export formats:

| Format | Supported | Example | Remark |
| --- | --- | --- | --- |
| bigquery  | TBD | TBD | |
| json  | TBD | TBD | |
| avro  | TBD | TBD | |
| parquet  | TBD | TBD | |
| iceberg  | TBD | TBD | |
| glue  | TBD | TBD | |
| redshift  | TBD | TBD | |
| spark  | TBD | TBD | |
| sqlserver  | TBD | TBD | |
| snowflake  | TBD | TBD | |
| databricks / unity  | TBD | TBD | |
| postgres  | TBD | TBD | |
| oracle  | TBD | TBD | |
| protobuf  | TBD | TBD | |
| trino  | TBD | TBD | |
| sql  | TBD | TBD | |
| sql-query  | TBD | TBD | |
| pydantic  | TBD | TBD | |
| dbt  | TBD | TBD | |
| odcs  | TBD | TBD | |
| rdf  | TBD | TBD | |

**Comment by jochenchrist** [comment]
OK, I think we should support the data type `map`.

We should add a hint that this data type may not be supported by all server types.
If the physical type cannot be deferred for a specific format or server type, then the config option can be used.

**Comment by jochenchrist** [comment]
If we introduce map, we also need to specify the `keyType` and `valueType`.

In Avro the key type always is string, but in other technologies, such as Unity, the key types can be specified.

**Comment by jochenchrist** [comment]
This is how we will model maps:


```
      warehouse_map:
        type: map
        keys:
          type: string
          description: The code of the warehouse
          example: "WH1"
        values:
          type: string
          description: The name of the warehouse
          example: "Warehouse 1"
```
