### ISSUE TITLE
Server Role

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#81]
List available roles per server type. USe description to give info what the role gives.

```yaml
servers:
  snowflake_prod:
    type: snowflake
    ...
    roles:
      - name: read-role
         description: My description
      - name: read-pii-role
         description: My description
```
